language: python
python:
  - 2.7
  - 3.4

notifications:
  email: false

# Install stuff
before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - export SEND_ERROR_MAIL=False
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
  # Work around for multiprocessing permission bug with Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose-cov
  - python setup.py install

# Run test
script:
  - nosetests -x -d -v --with-cov --cov gridmap --cov-config .coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /scratch/*

